### ISSUE TITLE
BenchMark

### ISSUE THREAD

**Issue by redhecker** [hezean/sustc#108]
### Describe your question

一些线下能过的测试线上是过不了的，请问这是为什么呢？
这样子debug起来会非常麻烦哦
难道有一些特殊情况你们不打算告诉我们，就看着我们做错吗？？？？？？？？

**Comment by magicoyong** [comment]
附议

**Comment by WhatWEat** [comment]
线下能过，线上理论能过，只是2组不同的随机生成的数据防止你们打表罢了

**Comment by sses7757** [comment]
@redhecker @magicoyong 
OJ上的题目和公开的测试文件是一样的，没有额外的特殊情况，建议检查一下是不是DDL之类的有问题

**Comment by hezean** [comment]
we've released all test data and straightly specify all corner cases in the javadoc to make it more possible for you to get a higher score, whereas we did not do so in the past few years, and the newly built oj platform is intended to help you finding problems early instead of being deducted after submitting your code

you already enjoyed the best ever project experience with the solid foundation we provided. while most students could get the same (expected) results in the oj, shouldn't you check your code before challenging us???



PLEASE DO THE CHECK:
1. confirm that you didn't write any platform dependent code
2. when testing locally, create the database as we specified `CREATE DATABASE sustc WITH ENCODING = 'UTF8' LC_COLLATE = 'C' TEMPLATE = template0;`
3. your submitted jar is the latest version, and your sql file can correctly initialize the database. some students modify the ddl in ide's console, without updating their sql file
