### ISSUE TITLE
Should we write the log in APIs?

### ISSUE THREAD

**Issue by Ray0v0** [hezean/sustc#11]
### Describe your question

In `DatabaseServiceImpl.sum()`, you write the log as `log.info("SQL: {}", stmt);`. However, in `DatabaseServiceImpl.truncate()`, you don't write the log. I'm wondering that should we write the log in every api we implemented? Does it count in the final grading? Is there any rules about that(when to use info, debug, error, how to record time, etc.)?

**Comment by hezean** [comment]
That's not required, but for debug purpose, I strongly suggest you to use loggers instead of printing to `System.out` or `System.err`.

We will turn the log level to `OFF` of your implementation when running the final benchmark, thus you won't need to delete these loggings and the performance won't be significantly affected. (but System.out.print always spends time)
