### ISSUE TITLE
[Benchmark] Something about multiThreads

### ISSUE THREAD

**Issue by maxinglo** [hezean/sustc#57]
### Describe your question

May I inquire about the specifications of the benchmark machine, such as the number of threads and available memory? This information is crucial in determining whether to use multiple threads. In scenarios involving multiple threads, it's possible that the main thread may proceed to the next stage before the data is fully imported. Would this potentially impact the test results?

**Comment by hezean** [comment]
the max heap memory of your program is 4g, and you basically don't need to worry about the number of threads, cuz even with a smaller heap limitation you can easily create thousands of threads.

you need to wait for threads to join during importing data, otherwise the correctness of the subsequent tests may be affected.

**Comment by maxinglo** [comment]
How many logical processor nodes are available for benchmark machine? This is crucial for determining the size of the thread pool to create.

**Comment by hezean** [comment]
there are 4
