### ISSUE TITLE
[Configuration] Configuration Issues with Third-Party Library

### ISSUE THREAD

**Issue by maxinglo** [hezean/sustc#60]
### Describe your question

During the development process, I utilized the MyBatis library. However, I couldn't figure out how to retrieve the database URL and account credentials from the `application.yml` file. As a result, I created a separate configuration file named `mybatis-config.xml` and stored the relevant information there. Would this pose any issues?

**Comment by hezean** [comment]
actually there's a spring-starter for mybatis that can read jdbc config from application.yml,
however, as mentioned below, you are NOT allowed to use mybatis since it's generally considered as an orm.

https://github.com/hezean/sustc/blob/2a596f950bb6b2132eb4f35347a3e61ebd14f168/sustc-api/build.gradle.kts#L17-L18

**Comment by maxinglo** [comment]
@hezean What would be the consequences if I use MyBatis? Would it result in penalties or a deduction of points? I need to assess whether I should rewrite my entire code.

**Comment by hezean** [comment]
May I first ask if you were in CS307 or CS213? I'll consult with the corresponding tutor for you.

**Comment by maxinglo** [comment]
@hezean CS307

**Comment by sses7757** [comment]
@maxinglo 
After consulting TA, our decision is that if you insist using ORM, you will get **50%** of your original **benchmark** score.
