### ISSUE TITLE
Why the HikariPool-1 - Connection is not available

### ISSUE THREAD

**Issue by alkane7** [hezean/sustc#77]
### Related module

Database

### What happened

[
![image](https://github.com/hezean/sustc/assets/133130114/836bd85c-f172-4d62-99f2-1404315b96dc)
](url)

### What you expected to happen

When I start benchmark, it will show this message. How can I solve it? 
Thank u!

**Comment by sses7757** [comment]
@alkane7 
It may be caused by several reasons. I can only list a few here according to my limited experience. If none of them works, you may consult TA or SA at lab class.
1. Database connection configuration at `application.yml` is incorrect or your user do not have enough privileges.
2. Forgetting to release connections or similar resources. The `HikariPool` is limited to 10 connections.
3. Your created database has a smaller connection limitation.

**Comment by sses7757** [comment]
@alkane7 
If you still have this error, you may continue to discuss this framework issue in discussion #83 together with other students with similar problems.
