### ISSUE TITLE
[PostVideoReq] Different data types of attribute "duration"

### ISSUE THREAD

**Issue by fz-zsl** [hezean/sustc#8]
### Related module

Code in sustc-api

### What happened

Attribute `duration` has different data type in `PostVideoReq` (`long`) and `VideoRecord` (`float`).

### What you expected to happen

Data type of `duration` in `PostVideoReq` should be changed as `float`.

**Comment by Ray0v0** [comment]
Also attribute sex in `RegisterUserReq `and `UserRecord `are different.

**Comment by sses7757** [comment]
@fz-zsl
The data type of duration in `PostVideoReq` is now changed to `float`, in [benchmark branch](https://github.com/hezean/sustc/tree/benchmark) waiting for PR.
However, the attribute `sex` in `RegisterUserReq` and `UserRecord` are inherently different since the latter is mainly used for import. You can create your own DTO if you prefer the attribute `sex` with `enum` data type.
