### ISSUE TITLE
ERROR: permission denied to set parameter "session_replication_role"

### ISSUE THREAD

**Issue by 7Sageer** [hezean/sustc#92]
### Describe your question

In my upload part, I use SET session_replication_role = 'replica' to temporarily remove foreign key. When I execute the online benchmark, I found that there's a error that "ERROR: permission denied to set parameter "session_replication_role"". Is it not permitted in benchmark? Should I remove this? If I doing so, what should I do to replace it?
<img width="490" alt="image" src="https://github.com/hezean/sustc/assets/125936732/e793c61a-18cd-471e-89b3-bcaba2d4b660">

**Comment by hezean** [comment]
<img width="1393" alt="Screenshot 2023-12-27 at 00 28 48" src="https://github.com/hezean/sustc/assets/49837965/7a1e91d5-e0b5-4331-ae1a-9f2338dc825e">

your program will run under a regular user who is nothing else than the owner of the test db, thus you won't have the permission to alter such system config. you need to find the solution by yourself since this is your project and we won't provide you such detailed guidance.
